import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1687874502309 implements MigrationInterface {
    name = 'Default1687874502309'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "TB_PESSOA" ("CODIGO_PESSOA" number GENERATED BY DEFAULT AS IDENTITY, "NOME" varchar2(256) NOT NULL, "SOBRENOME" varchar2(256) NOT NULL, "IDADE" number(3,0) NOT NULL, "LOGIN" varchar2(50) NOT NULL, "SENHA" varchar2(50) NOT NULL, "STATUS" number(3,0) NOT NULL, CONSTRAINT "PK_7cb2b7890cf20977a56b5ade442" PRIMARY KEY ("CODIGO_PESSOA"))`);
        await queryRunner.query(`CREATE TABLE "TB_ENDERECO" ("CODIGO_ENDERECO" number GENERATED BY DEFAULT AS IDENTITY, "NOME_RUA" varchar2(256) NOT NULL, "NUMERO" varchar2(10) NOT NULL, "COMPLEMENTO" varchar2(20), "CEP" varchar2(10) NOT NULL, "CODIGO_PESSOA" number, "CODIGO_BAIRRO" number, CONSTRAINT "PK_2006c133e7c56a888972bfccdc4" PRIMARY KEY ("CODIGO_ENDERECO"))`);
        await queryRunner.query(`CREATE TABLE "TB_UF" ("CODIGO_UF" number GENERATED BY DEFAULT AS IDENTITY, "SIGLA" varchar2(3) NOT NULL, "NOME" varchar2(60) NOT NULL, "STATUS" number(3,0) NOT NULL, CONSTRAINT "PK_339bb801620f29096d4e6e30032" PRIMARY KEY ("CODIGO_UF"))`);
        await queryRunner.query(`CREATE TABLE "TB_MUNICIPIO" ("CODIGO_MUNICIPIO" number GENERATED BY DEFAULT AS IDENTITY, "NOME" varchar2(256), "STATUS" number(3,0), "CODIGO_UF" number, CONSTRAINT "PK_e51036cbecd2061b3af7b2ddb46" PRIMARY KEY ("CODIGO_MUNICIPIO"))`);
        await queryRunner.query(`CREATE TABLE "TB_BAIRRO" ("CODIGO_BAIRRO" number GENERATED BY DEFAULT AS IDENTITY, "NOME" varchar2(256) NOT NULL, "STATUS" number(3,0), "CODIGO_MUNICIPIO" number, CONSTRAINT "PK_9833908deb14eab8c36f6850eb2" PRIMARY KEY ("CODIGO_BAIRRO"))`);
        await queryRunner.query(`ALTER TABLE "TB_ENDERECO" ADD CONSTRAINT "FK_7b04848cc0eda7c16d72a69ae9e" FOREIGN KEY ("CODIGO_PESSOA") REFERENCES "TB_PESSOA" ("CODIGO_PESSOA") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "TB_ENDERECO" ADD CONSTRAINT "FK_19905bbde841192c7fa90c0ec50" FOREIGN KEY ("CODIGO_BAIRRO") REFERENCES "TB_BAIRRO" ("CODIGO_BAIRRO") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "TB_MUNICIPIO" ADD CONSTRAINT "FK_5ffbefc831d79cc23b2a85bba3f" FOREIGN KEY ("CODIGO_UF") REFERENCES "TB_UF" ("CODIGO_UF") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "TB_BAIRRO" ADD CONSTRAINT "FK_f910210e141c8d8274e922ff80b" FOREIGN KEY ("CODIGO_MUNICIPIO") REFERENCES "TB_MUNICIPIO" ("CODIGO_MUNICIPIO") ON DELETE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "TB_BAIRRO" DROP CONSTRAINT "FK_f910210e141c8d8274e922ff80b"`);
        await queryRunner.query(`ALTER TABLE "TB_MUNICIPIO" DROP CONSTRAINT "FK_5ffbefc831d79cc23b2a85bba3f"`);
        await queryRunner.query(`ALTER TABLE "TB_ENDERECO" DROP CONSTRAINT "FK_19905bbde841192c7fa90c0ec50"`);
        await queryRunner.query(`ALTER TABLE "TB_ENDERECO" DROP CONSTRAINT "FK_7b04848cc0eda7c16d72a69ae9e"`);
        await queryRunner.query(`DROP TABLE "TB_BAIRRO"`);
        await queryRunner.query(`DROP TABLE "TB_MUNICIPIO"`);
        await queryRunner.query(`DROP TABLE "TB_UF"`);
        await queryRunner.query(`DROP TABLE "TB_ENDERECO"`);
        await queryRunner.query(`DROP TABLE "TB_PESSOA"`);
    }

}
