import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1687790224937 implements MigrationInterface {
    name = 'Default1687790224937'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "TB_UF" ("CODIGO_UF" number GENERATED BY DEFAULT AS IDENTITY, "SIGLA" varchar2(3) NOT NULL, "NOME" varchar2(60) NOT NULL, "STATUS" number(3) NOT NULL, CONSTRAINT "PK_339bb801620f29096d4e6e30032" PRIMARY KEY ("CODIGO_UF"))`);
        await queryRunner.query(`ALTER TABLE "TB_PESSOA" MODIFY "IDADE" number(3)  `);
        await queryRunner.query(`ALTER TABLE "TB_PESSOA" MODIFY "STATUS" number(3)  `);
        await queryRunner.query(`ALTER TABLE "TB_MUNICIPIO" MODIFY "STATUS" number(3)  `);
        await queryRunner.query(`ALTER TABLE "TB_BAIRRO" MODIFY "STATUS" number(3)  `);
        await queryRunner.query(`ALTER TABLE "TB_MUNICIPIO" ADD CONSTRAINT "FK_5ffbefc831d79cc23b2a85bba3f" FOREIGN KEY ("CODIGO_UF") REFERENCES "TB_UF" ("CODIGO_UF")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "TB_MUNICIPIO" DROP CONSTRAINT "FK_5ffbefc831d79cc23b2a85bba3f"`);
        await queryRunner.query(`ALTER TABLE "TB_BAIRRO" MODIFY "STATUS" number(3,0)  `);
        await queryRunner.query(`ALTER TABLE "TB_MUNICIPIO" MODIFY "STATUS" number(3,0)  `);
        await queryRunner.query(`ALTER TABLE "TB_PESSOA" MODIFY "STATUS" number(3,0)  `);
        await queryRunner.query(`ALTER TABLE "TB_PESSOA" MODIFY "IDADE" number(3,0)  `);
        await queryRunner.query(`DROP TABLE "TB_UF"`);
    }

}
